version: '3'

services:
  mysqldb:
    container_name: mysqldb
    image: mysql:8
    volumes:
      - /home/mysqlData:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root

  spring_app:
    container_name: achatproject
    image: achatproject
    restart: on-failure
    port:
      - 9090:9090
    depends_on:
      - mysqldb  
      
    
  

